### ISSUE TITLE
continue(2) in case statement

### ISSUE THREAD

**Issue by riwu** [SRL/Lape#16]
```
begin
  for 0 to 0 do
    for 0 to 1 do
    begin
      writeln('should be called only once');
      case 1 of
        1: continue(2);
      end;
    end;
end.
```

**Comment by nielsAD** [comment]
Thanks for reporting!

**Comment by riwu** [comment]
Wow the fix is so elaborate...looks like there's a long way to go before i can fix a lape bug myself :(

**Comment by nielsAD** [comment]
Feel free to ask questions when you want to know something about the source :)
