### ISSUE TITLE
weird bug

### ISSUE THREAD

**Issue by riwu** [SRL/Lape#18]
```
var
  a: tstringarray;

begin
  a:= GetDirectories('C:\Users\1\Desktop\x\');
  writeln(a);  //length == 1
  //writeln(length(a));  //uncommenting this results in error
  writeln(GetFiles('C:\' + a[1], 'txt'));
end. 
```

The directory 'C:\Users\1\Desktop\x\' contains only 1 folder, so a[1] should cause an out of bound error, but it isn't..

Execution result: http://i.imgur.com/GKyc76p.png

**Comment by WarPie** [comment]
This is the result of no range-checking in our current Lape. *Everything that does indexing will read from memory at the calculated position, even if it's "out of range" without yielding any warnings*. In this case when you read from a[1] you will get a random string containing what would look like noise.

I repeat all `myArray[index]` does is calculate a position in memory and read/writes to it, no range checking, no nothing, just `result := array_address+SizeOf(element)*index`. This CAN cause access violation if you do not have rights to that data, eg when it's owned by some other running program.

**Comment by riwu** [comment]
Ah i see...i thought range check was added sometime ago because i received access violations...so it's simply because i got lucky...

Yes when i uncomment WriteLn(Length(a)) i always get access violation, maybe somehow it shifted a[1]'s mem addr to outside of simba's memory.

Thanks, can be closed now.

**Comment by WarPie** [comment]
Range-checking is added into original lape, and requires the RangeChecks directive to be turned on. The release however contains some (unrelated) bugs that needs to be sorted before we can add this version of lape to Simba.
