### ISSUE TITLE
External results leaks.

### ISSUE THREAD

**Issue by slackydev** [SRL/Lape#20]
Well.. for some reason it seems that `lcoInitExternalResult` doesn't get toggled on in `IntializeFFI` it seems, or something else messes it up.. https://github.com/SRL/Lape/commit/97fe5ecb51644d8c684aa73644d085adf9dbda55

This (declined) [PR](https://github.com/SRL/Lape/pull/19/files) from what I remember worked like expected, so the issue is not an FFI issue from what I see. It's the flag that for some reason doesn't get enabled, or not at the right time at least.

**Comment by nielsAD** [comment]
Should be fixed with nielsAD/lape@d3e15ad6e49c08f8f62806af15885e531015876f .
